### ISSUE TITLE
command 'extension.rubyBlockToggle' not found

### ISSUE THREAD

**Issue by phuibonhoa** [elia/vscode-textmate#2]
When using the shortcut ⌃⇧+{ I get the error: `command 'extension.rubyBlockToggle' not found` 

I was expecting it would toggle the ruby block from `{ ... }` to `do ... end` and vice versa.

**Comment by elia** [comment]
Sorry, that one slipped in by mistake, I'll remove it, but if you're interested I'm using this extension to replicate that shortcut: https://marketplace.visualstudio.com/items?itemName=elliotlarson.ruby-around-the-block

**Comment by elia** [comment]
Fixed by https://github.com/elia/vscode-textmate/commit/d4f3dcb7c8ebed90cdf99adbaa171198e04898f0

**Comment by phuibonhoa** [comment]
> Sorry, that one slipped in by mistake, I'll remove it, but if you're interested I'm using this extension to replicate that shortcut: https://marketplace.visualstudio.com/items?itemName=elliotlarson.ruby-around-the-block

This is awesome, I have been looking for something like this! Thank you!
